# Generated by Django 4.2.7 on 2023-11-21 12:43
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='description',
        ),
    ]
